services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./ssl:/etc/nginx/ssl:ro
      - ./webroot:/etc/nginx/webroot
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    name: shared-net
    driver: bridge